[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF52840_xxAA --always-print-stacktrace"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"

[unstable]
# build-std = ["core", "panic_abort", "alloc"]
build-std = ["core", "alloc"]
build-std-features = ["optimize_for_size", "panic_immediate_abort", "core/turbowakers"]
# build-std-features = ["core/turbowakers"]
